image: atlassian/default-image:latest
pipelines:
    branches:
        test:
            - step:
                  name: Build & Deploy
                  deployment: test
                  script:
                      - ssh centos@$(echo $DEPLOY_SERVER_IP) 'bash -s' < ./test.sh
                      - echo 'Deploy success!!!'
        prod:
            - step:
                  name: Build & Deploy
                  deployment: production
                  script:
                      - ssh centos@$(echo $DEPLOY_SERVER_IP) 'bash -s' < ./prod.sh
                      - echo 'Deploy success!!!'
