version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: server-conference-chatting-api
        working_dir: /usr/src/app
        env_file:
            - .env
        restart: unless-stopped
        networks:
            - app-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - '4001:4001'
volumes:
    node_modules:
networks:
    app-network:
        driver: bridge
